### ISSUE TITLE
Copyright/License infringement

### ISSUE THREAD

**Issue by pardeike** [HerpDerpinstine/MelonLoader#4]
This repository has been copied from the original repository at https://github.com/Pardeike/Harmony but the README and LICENSE have been excluded. The original license is MIT and thus this copy failed to both include the license and provide proper credits.

**Comment by Slaynash** [comment]
Hello
This should be fixed with the next github push (we are using gitlab internally).
I have made some credits on the wiki already (see https://melonwiki.xyz/#/credits), but you're right that you should be credited in the repo too, and have the license included

**Comment by abbe** [comment]
Good job guys! First off stealing AtiLion's code, not implementing a proper patching system and then also copying Harmony? This is truly a state-of-the-art loader right here. xoxo

**Comment by Yaekith** [comment]
Oh I smell a DMCA coming

**Comment by Slaynash** [comment]
We never claimed Harmony was made by us. We are even stating on the wiki that it's made by pardeike.
Not having it in the repo was a mistake, that we are currently working on fixing.

**Comment by Yaekith** [comment]
too bad L

**Comment by Yaekith** [comment]
Slaynash, you should accept my friend request on discord or else I'll hit Melon Loader again kappa

**Comment by Yaekith** [comment]
Just wanna talk and you don't want to >:(

**Comment by NaaTiiVee** [comment]
Hello @pardeike ,

I added your LICENSE and README to the repo now.
Sorry for the inconvenience!

[Link to the commit](https://github.com/HerpDerpinstine/MelonLoader/commit/7bcbda6dc1b5c60ec35596c9f8d3d315edd3cb33)

**Comment by NaaTiiVee** [comment]
((Removed off-topic comments))
